version: '3'
services:

  controller:
    image: ngrinder/controller
    container_name: controller
    restart: always
    ports:
      - "8088:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/nginrder-controller

  agent:
    image: ngrinder/agent
    container_name: agent
    restart: always
    links:
      - controller
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 512m