name: Sns-CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          script: |
            echo "${{ secrets.APPLICATION_PROD }}" > /root/config/application-prod.yml
            /root/script/deploy.sh
